# -*- mode: python ; coding: utf-8 -*-
# Retained for one Python deprecation release; remove only after the retirement gate.

a = Analysis(
    ['run_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/presentation/gui/resources/icon.ico', 'src/presentation/gui/resources'),
        ('web-dist/waveform', 'web-dist/waveform'),
    ],
    hiddenimports=[
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'PySide6.QtCore',
        'src.application.coordinator',
        'src.infrastructure.global_config_service',
        'src.infrastructure.file_service',
        'src.infrastructure.config_service',
        'src.infrastructure.template_engine',
        'src.infrastructure.process_manager',
        'src.domain.services.dep_analyzer_service',
        'src.domain.services.port_parser_service',
        'src.domain.services.project_manager_service',
        'src.domain.services.sim_runner_service',
        'src.domain.services.verilog_utils',
        'src.domain.services.log_parser_service',
        'src.domain.services.vcd_parser_service',
        'src.domain.models.dependency',
        'src.domain.models.port',
        'src.domain.models.project',
        'src.domain.models.simulation',
        'src.presentation.gui.main_window',
        'src.presentation.gui.i18n',
        'src.presentation.gui.theme',
        'src.presentation.gui.worker_threads',
        'src.presentation.gui.widgets.project_panel',
        'src.presentation.gui.widgets.project_config_panel',
        'src.presentation.gui.widgets.log_panel',
        'src.presentation.gui.widgets.unified_module_panel',
        'src.presentation.gui.widgets.file_tree_panel',
        'src.presentation.gui.widgets.waveform_viewer_panel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='veriflow-gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['src/presentation/gui/resources/icon.ico'],
)
