# -*- coding: utf-8 -*-
"""
Testbench 生成器 — 根据配置生成 Verilog testbench 文件
"""

from pathlib import Path


class TestbenchGenerator:

    def generate(self, config: dict, output_dir: Path) -> str:
        name = config.get('name', 'tb_top')
        time_unit = config.get('time_unit', '1ns')
        time_precision = config.get('time_precision', '1ps')
        clocks_mhz = config.get('clocks_mhz', ['100'])
        reset_active_high = config.get('reset_active_high', False)
        reset_duration = config.get('reset_duration', '100')
        modules = config.get('modules', [])
        wave_file = config.get('wave_file', f'{name}.vcd')
        timeout = config.get('timeout', '1000000')

        lines = self._build(name, time_unit, time_precision, clocks_mhz,
                            reset_active_high, reset_duration,
                            modules, wave_file, timeout)

        filepath = output_dir / f'{name}.v'
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return str(filepath)

    def _build(self, name, time_unit, time_precision, clocks_mhz,
               reset_active_high, reset_duration,
               modules, wave_file, timeout):
        L = []

        L.append(f'`timescale {time_unit} / {time_precision}')
        L.append('')
        L.append(f'module {name};')
        L.append('')

        # ---- Clock signals ----
        for i, freq in enumerate(clocks_mhz):
            if not freq:
                continue
            try:
                freq_val = float(freq)
            except ValueError:
                freq_val = 100.0
            half_period = 1000.0 / (2.0 * freq_val)
            cname = f'clk_{i}' if i > 0 else 'clk'
            L.append(f'    reg {cname} = 0;')
            L.append(f'    always #({half_period:.1f}) {cname} = ~{cname};')
            L.append('')

        # ---- Reset signal ----
        rst_signal = 'rst' if reset_active_high else 'rst_n'
        rst_val_init = "1'b1" if reset_active_high else "1'b0"
        rst_val_release = "1'b0" if reset_active_high else "1'b1"
        L.append(f'    reg {rst_signal} = {rst_val_init};')
        L.append('    initial begin')
        try:
            dur = int(reset_duration or '100')
        except ValueError:
            dur = 100
        L.append(f'        #({dur}) {rst_signal} = {rst_val_release};')
        L.append('    end')
        L.append('')

        # ---- Collect all ports across modules, merge same-name ----
        # Build exclude set: clock/reset signals already generated by testbench
        exclude_signals = {rst_signal}
        for i, freq in enumerate(clocks_mhz):
            if not freq:
                continue
            cname = f'clk_{i}' if i > 0 else 'clk'
            exclude_signals.add(cname)

        merged_signals = {}
        all_parsed = []
        for mod in modules:
            filepath = mod.get('filepath', '')
            ports, params = self._parse_module(filepath)
            all_parsed.append((mod, ports, params))
            port_signals = mod.get('port_signals', {})
            for port in ports:
                sig_name = port_signals.get(port.name, port.name)
                if sig_name in exclude_signals:
                    continue
                existing = merged_signals.get(sig_name)
                if existing is None:
                    merged_signals[sig_name] = port
                else:
                    w_old = self._width_bits(existing)
                    w_new = self._width_bits(port)
                    if w_new > w_old:
                        merged_signals[sig_name] = port

        # ---- Generate shared signal declarations ----
        input_signals = {}
        output_signals = {}
        inout_signals = {}
        for sig_name, port in merged_signals.items():
            direction = port.direction
            width_str = port.get_width_str()
            if direction == 'input':
                input_signals[sig_name] = width_str
            elif direction == 'inout':
                inout_signals[sig_name] = width_str
            else:
                output_signals[sig_name] = width_str

        if input_signals:
            L.append('    // ---- Shared DUT input signals (reg) ----')
            for sig, w in sorted(input_signals.items()):
                wire_type = 'reg'
                decl = f'    {wire_type} {w} {sig};' if w else f'    {wire_type} {sig};'
                L.append(decl)
            L.append('')

        if output_signals:
            L.append('    // ---- Shared DUT output signals (wire) ----')
            for sig, w in sorted(output_signals.items()):
                decl = f'    wire {w} {sig};' if w else f'    wire {sig};'
                L.append(decl)
            L.append('')

        if inout_signals:
            L.append('    // ---- Shared DUT inout signals (wire) ----')
            for sig, w in sorted(inout_signals.items()):
                decl = f'    wire {w} {sig};' if w else f'    wire {sig};'
                L.append(decl)
            L.append('')

        # ---- DUT instantiations ----
        for mod, ports, params in all_parsed:
            mod_name = mod.get('module_name', 'unknown')
            inst_name = mod.get('instance_name', f'u_{mod_name}')
            port_signals = mod.get('port_signals', {})
            param_values = mod.get('param_values', {})

            L.append(f'    // ---- DUT: {mod_name} ({inst_name}) ----')

            has_params = len(params) > 0
            if has_params:
                L.append(f'    {mod_name} #(')
                for i, param in enumerate(params):
                    pvalue = param_values.get(param.name, param.value)
                    comma = ',' if i < len(params) - 1 else ''
                    L.append(f'        .{param.name}({pvalue}){comma}')
                L.append(f'    ) {inst_name} (')
            else:
                L.append(f'    {mod_name} {inst_name} (')

            for i, port in enumerate(ports):
                sig_name = port_signals.get(port.name, port.name)
                comma = ',' if i < len(ports) - 1 else ''
                L.append(f'        .{port.name}({sig_name}){comma}')

            L.append('    );')
            L.append('')

        # ---- $dump ----
        L.append('    initial begin')
        L.append(f'        $dumpfile("{wave_file}");')
        L.append(f'        $dumpvars(0, {name});')
        L.append('    end')
        L.append('')

        # ---- Timeout ----
        try:
            t = int(timeout or '1000000')
        except ValueError:
            t = 1000000
        L.append('    initial begin')
        L.append(f'        #({t}) $finish;')
        L.append('    end')
        L.append('')
        L.append('endmodule')
        L.append('')

        return L

    def _width_bits(self, port) -> int:
        if port.width_msb is not None and port.width_lsb is not None:
            return abs(port.width_msb - port.width_lsb) + 1
        if port.width:
            try:
                m = __import__('re').match(r'\[(\d+):(\d+)\]', port.width)
                if m:
                    return abs(int(m.group(1)) - int(m.group(2))) + 1
            except Exception:
                pass
        return 1

    def _parse_module(self, filepath: str):
        if not filepath:
            return [], []
        try:
            from src.infrastructure.file_service import FileService
            from src.domain.services.port_parser_service import PortParserService
            fs = FileService()
            parser = PortParserService(fs)
            info = parser.parse_file(filepath)
            return list(info.ports), list(info.parameters)
        except Exception:
            return [], []
